### ISSUE TITLE
learned_nsn.model and learned_ndn.model cann't be found

### ISSUE THREAD

**Issue by cyzxidian** [funalab/QCANet#1]
I have downloaded the learned_nsn.model and learned_ndn.model. I ran the command "python qca_net.py --scaling_seg --scaling_det". But one error said "Not found ../models/p128/learned_nsn.model".

**Comment by tamasbalassa** [comment]
Same issue here. Couldn't find any solution yet.
The .model files are not corrupted. Maybe the issue is coming from the _chainer_ package?

**Comment by cyzxidian** [comment]
Exactly. I have solved this problem by installing an older version of chainer (1.24.0).

**Comment by tokkuman** [comment]
Thank you for pointing us the issue.
We changed the learned model so that it will be compatible with several versions of Chainer.
We also confirmed that the new learned model works with the most updated version of Chainer (v 5.0.0).
Along with this change, we updated the README.

Thanks :-)
