### ISSUE TITLE
split_list in example dataset??

### ISSUE THREAD

**Issue by sushmanthreddy** [funalab/QCANet#10]
@tokkuman is there anything we have to fill in split_list files?

nothing is mentioned about that directory in repo?

pls provide anything about it..

**Comment by sushmanthreddy** [comment]
@tokkuman can u pls reply for this issue??
i have been trying to understand this file but couldn't understand very well

**Comment by tokkuman** [comment]
@sushmanthreddy Sorry for the late reply.
The split_list files should contain the file names (images) used for training or validation, separated by lines.
For example, `example_datasets/split_list/train.txt` contains the file name for training (`8_cell_stage.tif`).

**Comment by sushmanthreddy** [comment]
oh got it ...thanks for the reply.. @tokkuman
