### ISSUE TITLE
Can't load trained model files in qca_net.py

### ISSUE THREAD

**Issue by Arkkienkeli** [funalab/QCANet#3]
Hello, it is me again. 
I did run the training scripts and obtained folders with result. 
```
python train_ndn.py -i ../datasets/ --opt_method Adam -g 0 --epoch 40 --patchsize 64
python train_nsn.py -i ../datasets/ --opt_method Adam -g 0 --epoch 40 --patchsize 64
```
Then I want to run _qca_net.py_ script to get segmentations (let it be the same dataset).

```
python qca_net.py -i ../dataset/ -ms ./result_train_nsn_Dec7Fri_2018_112418/NSN_Recall_hdf5_p64_k2.model  -md ./result_train_ndn_Dec7Fri_2018_090725/NDN_Fmeasure_hdf5_p64_k2.model
```
I get the error 
```
Not Found: ./result_train_nsn_Dec7Fri_2018_112418/NSN_Recall_hdf5_p64_k2.model
Usage : Input File Path of Model (ex ./hoge.model)
```
Then I go to loadModel in _utils.py_ and get the exact exception:
```
Failed to interpret file './result_train_nsn_Dec7Fri_2018_112418/NSN_Recall_hdf5_p64_k2.model' as a pickle
```
What could be the problem? 
Also, what are the .model files I get with suffix IoU\Precision\Recall, it mean this model got best score in this metric? 
Thank you.

**Comment by Arkkienkeli** [comment]
Works now, thank you.

**Comment by tokkuman** [comment]
I'm sorry. The cause was new bugs.
`utils.py` loaded `.npz` model as `.hdf5` model.
After the modification commit, `utils.py` can load any models (`.npz` or `.hdf5`).
Moreover, the model to be saved is unified to `.npz`.

Exactly! Each model means stated by you.

Thank you:-)

**Comment by tokkuman** [comment]
I'm glad!
