### ISSUE TITLE
Size of images

### ISSUE THREAD

**Issue by Arkkienkeli** [funalab/QCANet#4]
Hi, I am trying to perform training on 150x150 stacks, but it crashes with a resizing error.
When I crop this image to 128x128, it works fine.
But I noticed that in your example dataset images are of size 122x120.
What are the requirements for image size?
Any possibility to apply for any image size (limited only by GRAM)?
Thank you.

**Comment by tokkuman** [comment]
Hi, Arkkienkeli

Thank you for your interest in my work!
Although there are restrictions on the memory of the hardware, there is no restriction on the image size.
Could you tell me the command and error messages when you were trying to perform training?

**Comment by Arkkienkeli** [comment]
Hi tokkuman,

The command was:
```
python train_nsn.py -i ../dataset_test/ --opt_method Adam -g 0 --epoch 40 --patchsize 64
```
And the stacktrace
```
  File "train_nsn.py", line 282, in <module>
    main()
  File "train_nsn.py", line 251, in main
    train_eval, test_eval, bs = trainer.NSNTraining(trainIdx, testIdx, xlist, ylist, k)
  File "/home/nikitam/QCANet/src/lib/trainer.py", line 55, in NSNTraining
    TP, TN, FP, FN, train_sum_loss = self._trainer(opt_nsn, trainIdx, xlist, ylist, train=True, epoch=epoch)
  File "/home/nikitam/QCANet/src/lib/trainer.py", line 159, in _trainer
    x_patch = x_patch.reshape(1, 1, self.patchsize, self.patchsize, self.patchsize).astype(np.float32)
ValueError: cannot reshape array of size 0 into shape (1,1,64,64,64)
```

**Comment by tokkuman** [comment]
I updated the code that seems to be this cause.
Please try running the command after merge the update as follow.
```
% cd /home/nikitam/QCANet
% git fetch
% git merge origin/master
% cd src
% python train_nsn.py -i ../dataset_test/ --opt_method Adam -g 0 --epoch 40 --patchsize 64 --paddingsize 192
```

**Comment by Arkkienkeli** [comment]
It works now, thank you.
