### ISSUE TITLE
python versions

### ISSUE THREAD

**Issue by sushumereddy** [funalab/QCANet#8]
@funasoul @tokkuman  does it work with newer version of python?how can I work with newer version with python??

and another thing is does trained model of nsn and ndn trained on c elegans data??

**Comment by tokkuman** [comment]
@sushumereddy Sorry for the late reply, we have already confirmed that python version up to 3.7 works fine.
So 3.8 should also work, but if you have any problems, please contact us.

The trained models (learned_nsn.npz, learned_ndn.npz) that we have made available are trained on mouse data.
The models trained on C. elegans are ready to be available, so please wait a little longer.
